### ISSUE TITLE
VendorID&ProductID out of range

### ISSUE THREAD

**Issue by mo10** [LibUsbDotNet/LibUsbDotNet#10]
Hi,

I use "Info.Descriptor.VendorID" got a wrong value.
Info.Descriptor.VendorID and Info.Descriptor.VendorID uses an **short** type,Its maximum range is 32767,but my usb device ProductID is 0xEFE8(61416).
61416 over the short type range.
How should I get the right ProductID value?

Thanks!

**Comment by cristianst85** [comment]
Hi @mo10,

I had a similar issue when needed to find a device that had a PID value (0xca01) that exceeded the **short** type range and I've used this workaround instead:

`profile.DeviceDescriptor.ProductID == unchecked((short)0xca01))`

**Comment by mo10** [comment]
Thank you, @cristianst85 

I found another way to solve the problem,  `UsbRegistry.Pid` and `UsbRegistry.Vid` can get the right value:
`public virtual int Pid { get; }`
and
`public virtual int Vid { get; }`

See:http://libusbdotnet.sourceforge.net/V2/html/a432caef-6b30-6fd2-3475-146c30266188.htm

**Comment by mcuee** [comment]
I will re-open this as this seems to be a common question.

**Comment by mcuee** [comment]
This should be fixed by #215.
