### ISSUE TITLE
demo code for old version

### ISSUE THREAD

**Issue by Federau** [LibUsbDotNet/LibUsbDotNet#112]
Hello,I could not useusbcontext in version 2.2.29;  where could I get demo code for old version(2.2.29)?

**Comment by doug62** [comment]
@Federau You can set the branch here to something around that date and pull it...  If you are new to source control take a look at sourcetree, you could also download a zip from here.

**Comment by mcuee** [comment]
You can also take a look at the release history.
https://www.nuget.org/packages/LibUsbDotNet/

**Comment by mcuee** [comment]
@Federau You can look at v2 branch. It now works very well.
