### ISSUE TITLE
USB Capture Cards

### ISSUE THREAD

**Issue by BobbyShoe** [LibUsbDotNet/LibUsbDotNet#118]
Should the library work with USB Capture Cards?  I have a USB Capture Card that is identified as a Camera in Device Manager.  I tried to run the ReadIsochronous example, and updated the UsbDeviceFinder with the appropriate VID and PID values, however the device is not found on this line of code

UsbRegDeviceList regList = UsbDevice.AllDevices.FindAll(MyUsbFinder);

Thanks for the help.

**Comment by mcuee** [comment]
You have to install WinUSB or libusbk driver in order for libusb/libusbdotnet to use a USB device under Windows.
https://zadig.akeo.ie/

But I am not so sure if libusbdotnet supports isoc transfer under Windows or not yet. libusb itself has the support of WinUSB isoc transfer but got multiple problems. It also has libusbk isoc transfer which works a bit better.

All in all, it is difficult to get isoc transfer to work well with libusb under Windows.
