### ISSUE TITLE
Unable to get the serial number and name of devices

### ISSUE THREAD

**Issue by toffuser** [LibUsbDotNet/LibUsbDotNet#122]
Running this command :             var allDevices = UsbDevice.AllDevices;

![image](https://user-images.githubusercontent.com/3202063/101069541-26472600-3568-11eb-978b-b70eb1cd6576.png)

I am unable to see what is the serial number or manufacturer name...(it display this Љ) but if I run this command in linux : usb-devices 
I can see what are the devices serial number. 

I run LibUsbDotNet with a .net5 application on a raspberryPi (Debian)

**Comment by mcuee** [comment]
Sorry just wondering how you build with .NET5 under Raspberry Pi. There seem to be issue building libusbdotnet under .Net 5.0.

**Comment by mcuee** [comment]
> Sorry just wondering how you build with .NET5 under Raspberry Pi. There seem to be issue building libusbdotnet under .Net 5.0.

I am fine with the latest git now.

**Comment by mcuee** [comment]
PR #203 should have fix this issue. I will close this for now.

@toffuser 

Please try latest v2 branch to see if you still have issues or not. If you still have the issues, please reopen.
