### ISSUE TITLE
Control Transfer Failure on Windows

### ISSUE THREAD

**Issue by Proclivis** [LibUsbDotNet/LibUsbDotNet#13]
I have an application working on Linux with 2.2.8 (using Core) that fails on Windows with 2.2.8 (using Core). In order to make Windows work at all I have:

```
UsbDevice.ForceLibUsbWinBack = true;
```
The application is downloading an image to an FX3 and then resetting the device. The download of the image works, as seen by a Beagle. But the final control transfer that resets it fails.

The code fails here:

```
            IntPtr bufPtr = Marshal.AllocHGlobal((int)buflen);
            Marshal.Copy(buf, 0, bufPtr, (int)buflen);
            UsbSetupPacket packet = new UsbSetupPacket(0x64, 0xA0, (int) (Address & 0x0000FFFF), (int) (Address >> 16), 4);
            int len;
            bool ok = MyUsbDevice.ControlTransfer(ref packet, bufPtr, (int) buflen, out len);
            Marshal.Copy(bufPtr, buf, 0, (int)buflen);
            Marshal.FreeHGlobal(bufPtr);
```
The packet contains the following values (Windows):
Index 16385
Length 4
Request 160
RequestType 64 (DIR_TO_DEVICE REQ_VENDOR TGT_DEVICE
Value -21096

And when the command runs on Windows, it returns false, whereas on Linux it returns true. The Beagle shows that the control transfer does not occur on Windows, but it does on Linux. This same code is called a hundred times to download the image and a Beagle traces shows it is all working fine until this specific transfer.

The buf variable is length 1, and buflen is 0.

I have tested with 2.2.9 (using standard) and see the same behavior. I have looked at the packet on Linux and it matches Windows.

I should also point out that Linux is Ubuntu 16 TLS (64bit)  on a laptop, and Windows is Win 10 64bit on a VMWare VM on the same Ubuntu laptop.

Is there a way to examine some error code?
Is there some logging I can enable?

For completeness, here is the code for opening the device:

```
        public Boolean Open()
        {
            try
            {
                // Find and open the usb device.
                MyUsbDevice = UsbDevice.OpenUsbDevice(MyUsbFinder);

                // If the device is open and ready
                if (MyUsbDevice == null) throw new Exception("Device Not Found.");

                // If this is a "whole" usb device (libusb-win32, linux libusb)
                // it will have an IUsbDevice interface. If not (WinUSB) the 
                // variable will be null indicating this is an interface of a 
                // device.
                IUsbDevice wholeUsbDevice = MyUsbDevice as IUsbDevice;
                if (!ReferenceEquals(wholeUsbDevice, null))
                {
                    // This is a "whole" USB device. Before it can be used, 
                    // the desired configuration and interface must be selected.

                    // Select config #1
                    wholeUsbDevice.SetConfiguration(1);

                    // Claim interface #0.
                    wholeUsbDevice.ClaimInterface(0);

                    // open read endpoint 1.
                    reader = MyUsbDevice.OpenEndpointReader(ReadEndpointID.Ep01);

                    // open write endpoint 1.
                    writer = MyUsbDevice.OpenEndpointWriter(WriteEndpointID.Ep01);
                }
            }
            catch (Exception ex)
            {
                return false;
            }
            return true;
        }
```

If I load the image from Linux, my application that runs after re-enumeration works on Windows fine. It seems to be related to the very specific packet.

**Comment by qmfrederik** [comment]
This is very likely an issue with libusbK. You're best off asking on the libusb-win32 mailing list or StackOverflow.
