### ISSUE TITLE
Where can I find the version of libusb supported by LibUsbDotNet?

### ISSUE THREAD

**Issue by mingpepe** [LibUsbDotNet/LibUsbDotNet#134]
For example,  for LibUsbDotNet 2.2.29, is it support to libusb1.0.22?
I can only check the release date to guess it.
Is there any document about it?

**Comment by mcuee** [comment]
By right the version of libusb should not matter and you should try to use the latest version which is 1.0.24.
1.0.25rc1 will come soon.

**Comment by mcuee** [comment]
I can not seem to build this repo. However, just FYI, I can use libusb 1.0.24 or libusb git head with the old libusbdotnet 2.2.8. released back in Oct 2010 (almost 10 years ago).

**Comment by mcuee** [comment]
I tested 1.0.24 and latest libusb git, both work fine with libusbdotnet (latest main line, or latest v2 branch).
