### ISSUE TITLE
The visual basic example should close the device after reading the information

### ISSUE THREAD

**Issue by pigdragon** [LibUsbDotNet/LibUsbDotNet#136]
If usbRegistry.Open(MyUsbDevice) Then
    ....
   MyUsbDevice.Close()  'should close the device.
end if

**Comment by mcuee** [comment]
Just wondering which version of libusbdotnet are you looking at? Latest git main and v2 branch no longer have the vb examples.

**Comment by mcuee** [comment]
Closing this issue.
