### ISSUE TITLE
How to use on Linux running .NET Core?

### ISSUE THREAD

**Issue by grandchamp** [LibUsbDotNet/LibUsbDotNet#14]
Hi.
I'm trying to use it on Ubuntu with .NET Core, but i'm receiving "libusb-1.0 library not found.  This is often an indication that libusb-1.0 was installed to '/usr/local/lib' and mono.net is not looking for it there. To resolve this, add the path '/usr/local/lib' to '/etc/ld.so.conf' and run 'ldconfig' as root. (http://www.mono-project.com/DllNotFoundException)".

Looking at the code, all the `[DllImport]`are using `libusb-1.0.dll` and not a .so file. How to make it work?

**Comment by TAGC** [comment]
[This might solve it for you](https://stackoverflow.com/a/41765048/1636276)
