### ISSUE TITLE
libusb-1.0.dll DllNotFoundException

### ISSUE THREAD

**Issue by ttrfanatic** [LibUsbDotNet/LibUsbDotNet#149]
I'm trying to add the LibUsbDotNet to my existing project and I'm running into an issue where the code seems to not be loading the libusb dll. I'm running on Windows 10, using VS 2019 and targeting .NET Framework 4.8. I have tried using the NuGet package (both the latest stable and pre-release) as well as cloned the repo and just referenced the LibUsbDotNet project as well. I have downloaded the libusb-1.0.dll and have placed it directly in the folder where the executable resides. Also, I am reference the LibUsbDotNet assembly from my class library which is being used in a different project. (And yes I put the libusb-1.0.dll in the executable folder).

I have run the example (ShowInfo) successfully so my suspicion is that it has to do with my project not be a .netcore project but I don't know if I'm that is correct or not. I even tried created a new console app (targeting .net 4.8) and using it there and I get the same DllNotFoundException.

I'm a very newb at using LibUsbDotNet so any help would be greatly appreciated.

**Comment by meronz** [comment]
Same happening on Fedora34. Creating a symlink to the correct library worked:
```
sudo ln -s /usr/lib64/libusb-1.0.so.0 /usr/lib64/libusb-1.0.so 
```

**Comment by neilenns** [comment]
I'm having the same issue with a .NET 4.5 application. It doesn't matter that I have libusb-1.0.dll in the `bin` folder, I always get an error saying the DLL can't be found.

**Comment by neilenns** [comment]
After hours spent on this I finally realized it's because the library is trying to open `libusb-1.0` not `libusb-1.0.dll`. If I rename the dll so it doesn't have the extension on it I am finally able to get the DLL to load and some code to run.
