### ISSUE TITLE
libusb not working

### ISSUE THREAD

**Issue by shenxianmq** [LibUsbDotNet/LibUsbDotNet#150]
when i use "dotnet SysDVR-Client.dll usb --rtsp"

then i get err like this :
Error:
  An assembly specified in the application dependencies manifest (SysDVR-Client.deps.json) was not found:
    package: 'SysDVR.LibUsbDotNet', version: '1.0.0'
    path: 'runtimes/osx-x64/native/libusb-1.0.0.dylib'

i really want to know how can i fix this problem

**Comment by mcuee** [comment]
If you use a prebuilt application, you have to ask the application developer, they are supposed to bundle the libusb runtime library in their app.

Normally you install libusb under macOS using homebrew or macports. But in this case, probably they hardcode the path. So if you build the application by using the source code, you need to put the libusb runtime in that particular location.
