### ISSUE TITLE
Timeout error on `_writer.Write() or _writer.Read()`

### ISSUE THREAD

**Issue by TheAirBlow** [LibUsbDotNet/LibUsbDotNet#152]
Code is [here](https://github.com/Samsung-Loki/Hreidmar).
It always spits out "MonoLibUsb -7: Timeout error", while all other calls are successful, as their return value is checked. 
Everything is as intended. What am I doing wrong? Also, this is a duplicate as other issue that was closed with more information.
This should be an issue with my brain, not libusb and LibUsbDotNet as Heimdall successfully connects to the device.

**Comment by TheAirBlow** [comment]
I think I should follow [docs](http://libusbdotnet.sourceforge.net/V2/Index.html) -> MonoLibUsb -> Bulk Read/Write.

**Comment by mcuee** [comment]
So there is no issue on libusbdotnet. Thanks.
