### ISSUE TITLE
Regarding testing read and Write data to and from device

### ISSUE THREAD

**Issue by Mamatha-Tech** [LibUsbDotNet/LibUsbDotNet#156]
Hi, Iam able to get the device list using LibUSB.Net package, and able to open the endpoint to read and write. Can you please let us know how to test the read and write data to and from USB device and PC.
Is there any sample code or application(apk) to install in USB device so that we can test the data trsnsfer from PC to USB device and viceversa.

Thanks,
Mamatha

**Comment by mcuee** [comment]
You have to know the device communication protocol. The examples are here.
https://github.com/LibUsbDotNet/LibUsbDotNet/tree/master/src/Examples

BTW, this github repo is for issue reporting and not really about question answers. So I will close this one.
