### ISSUE TITLE
Issue Related To LibUsbDotNet.WinUsb.Internal.WinUsbAPI.WinUsb_GetOverlappedResult()

### ISSUE THREAD

**Issue by erkkinen** [LibUsbDotNet/LibUsbDotNet#16]
I was getting the stack trace bellow when using LibUsbDotNet when sending and receiving data from a UsbDevice that would disconnect and I would have to reconnect to it. Reconnecting would work, but when the application would end and Garbage Collector would attempt to clean it up I would get the System.ObjectDisposedException.

Unhandled Exception: System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at LibUsbDotNet.WinUsb.Internal.WinUsbAPI.WinUsb_GetOverlappedResult(SafeHandle InterfaceHandle, IntPtr pOVERLAPPED, Int32& lpNumberOfBytesTransferred, Boolean Wait)
   at LibUsbDotNet.Internal.OverlappedTransferContext.Wait(Int32& transferredCount, Boolean cancel)
   at LibUsbDotNet.Main.UsbTransfer.Dispose()
   at LibUsbDotNet.Main.UsbTransfer.Finalize()

This stackoverflow thread seems to be related to this issue. https://stackoverflow.com/questions/20841117/libusbdotnet-error-on-exiting-wpf-application-safe-handle-has-been-closed

Adding the code provided by the answer Alex Klaus provides appears to work as the exception went away, but instead of LibUsbDotNet.Internal.LibUsb.LibUsbAPI.GetOverlappedResult(), I added it to LibUsbDotNet.WinUsb.Internal.WinUsbAPI.GetOverlappedResult(). It is probably applicable also where the original poster said to put the fix, but I haven't tested that as I didn't have an applicable use case/ test case for it. The attached patch is the fix I am proposing for this issue, which should change the code as follows.

Code Before Patch: 
`public override bool GetOverlappedResult(SafeHandle InterfaceHandle, IntPtr pOVERLAPPED, out int numberOfBytesTransferred, bool Wait) { return WinUsb_GetOverlappedResult(InterfaceHandle, pOVERLAPPED, out numberOfBytesTransferred, Wait); }`

Code After Patch:
`public override bool GetOverlappedResult(SafeHandle InterfaceHandle, IntPtr pOVERLAPPED, out int numberOfBytesTransferred, bool Wait) 
{ 
     if (!InterfaceHandle.IsClosed) 
     {
          return WinUsb_GetOverlappedResult(InterfaceHandle, pOVERLAPPED, out numberOfBytesTransferred, Wait);
     }
     else
     {
          numberOfBytesTransferred = 0;
          return true;
     }			
}`

Please let me know if you any additional questions about this bug/ if there is a different process to get this fix in please let me know.

[WinUsbIsClosed.txt](https://github.com/LibUsbDotNet/LibUsbDotNet/files/1293906/WinUsbIsClosed.txt)

https://github.com/LibUsbDotNet/LibUsbDotNet/blob/8c4e7eb5f4630bf8fa54a79f9d40287562e2f671/stage/LibUsbDotNet/WinUsb/Internal/WinUsbAPI.cs#L189

**Comment by qmfrederik** [comment]
@erkkinen The easiest way to get a fix in would be to just create a pull request. To create a pull request, fork this repository on GitHub, make the change to your fork, and then submit a PR.
