### ISSUE TITLE
In Linux system LibUsbDotNet.Info.UsbBaseInfo.CustomDescriptors issue

### ISSUE THREAD

**Issue by vitalijusb85** [LibUsbDotNet/LibUsbDotNet#164]
Hi, 
In the Linux system, LibUsbDotNet.Info.UsbBaseInfo.CustomDescriptors can't recognize all custom descriptors. For example, I add a print screen.  In Windows, the system works well.
![image](https://user-images.githubusercontent.com/34238776/176845879-865665d4-e4b0-4659-9505-370b50ddb6e6.png)

**Comment by mcuee** [comment]
Did you set up the right udev rules for your device?

**Comment by vitalijusb85** [comment]
Hi,
yes, I set rules for the device:
SUBSYSTEM=="usb", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="df11", MODE="0666". 
The problems are the same.
But whit dfu-utils it works on Linux.

**Comment by benedekkupper** [comment]
This is not specific to Linux, but more related to interfacing libusb driver instead of WinUsb. By manually replacing WinUsb driver to libusb-win32 (using Zadig tool), the above mentioned issue occurs on Windows as well.

**Comment by mcuee** [comment]
PR #203 should have fix this issue. I will close this for now.

@vitalijusb85 

Please try latest v2 branch to see if you still have issues or not. If you still have the issues, please reopen.
