### ISSUE TITLE
Are there any plans to upgrade to .net6?

### ISSUE THREAD

**Issue by GreenShadeZhang** [LibUsbDotNet/LibUsbDotNet#169]
.net6 is currently a unified multi-platform version, is it possible to upgrade to .net6 and then replace the mono implementation?

**Comment by wangzhentian** [comment]
same question here

**Comment by GreenShadeZhang** [comment]
> same question here

Recently I passed the test by modifying the source code of the v2 branch of the project to .net6 and then combined with the Raspberry Pi zero 2w test in Ubuntu 2022.

**Comment by mcuee** [comment]
Please help to create pull request, thanks.

**Comment by GreenShadeZhang** [comment]
> same question here

I submitted a PR updating the framework

**Comment by mcuee** [comment]
PR #172 has been merged for v2 branch.
* #172
