### ISSUE TITLE
UsbEndpointReader  DataReceived event not working on linux

### ISSUE THREAD

**Issue by pekovbg** [LibUsbDotNet/LibUsbDotNet#173]
Hello , I try to using library on Ubuntu 22.04.1 LTS, but Receive Event not working if starting app from gui , but if starting app from ssh console , all working.
And MyUsbDevice.UsbRegistryInfo.IsAlive not working and app crashed

**Comment by mcuee** [comment]
You have to provide more details like the code snippets so that others can help you.
