### ISSUE TITLE
Identifying two devices with the same VendorId and ProductId

### ISSUE THREAD

**Issue by RobertoBiundo** [LibUsbDotNet/LibUsbDotNet#176]
Is there a way of identifying and keeping track of two devices with the same ProductId and VendorId if the devices do not provide a Serial Number?

As an example I have a task that runs every 1sec to figure out if there is a new dongle connected to my mac. 
If there is one I can identity it, open it, clone it and close it. I keep track of the cloned dongle myself. But when re-discovering I cannot find a way if the device is already in my list of "connected dongles" or if it is a new one, or if the one I have has been disconnected. 

I have something list this at the moment.

```
        using var context = new UsbContext();
        using var allDevices = context.List();
        
        var dongleDevices = allDevices
            .Where(device => DongleConstants.DongleIdentificationParameters.Any(parameter => parameter.VendorId == device.VendorId && parameter.ProductId == device.ProductId))
            .ToList();
        
        foreach (var usbDevice in dongleDevices)
        {
            if (!usbDevice.TryOpen()) return;
            
            var usbDeviceClone = usbDevice.Clone();
            
            var device = new Dongle
            {
                UsbDevice = usbDeviceClone
            };

            usbDevice.Close();
            device.UsbDevice.Open();
            
            Dongles.Add(device);
        }
```

As you can see. If i re-run this code I don't want to add to my 'Dongles' list the device if it is already there. But I can't seem to find something to match it against in the case that I have two of the same dongles connected.

**Comment by RobertoBiundo** [comment]
I know that there is an 'Address' in the UsbDevice class, but here you only get an IUsbDevice. I can't seem to find a way of getting a hold of the Address. I could probably use this to say, hey, that is the same device as before, i will not add it again, as well as saying, look, the device that i have on my list no longer exists.

**Comment by sdijoseph** [comment]
I think using a pairing of the BusNumber and list of PortNumbers of each UsbDevice should eliminate duplicates. However, right now the PortNumbers property doesn't work (see PR #192 ). In the meantime, you can use PortNumber, but this will only give unique devices if the UsbDevice only has one port number.

Using your above code:
```
using var context = new UsbContext();
using var allDevices = context.List();

    var dongleDevices = allDevices
        .Where(device => DongleConstants.DongleIdentificationParameters.Any(parameter => parameter.VendorId == device.VendorId && parameter.ProductId == device.ProductId))
        .ToList();
    
    foreach (var usbDevice in dongleDevices)
    {
        bool dongleAlreadyExists = Dongles.Any(device => device.BusNumber == usbDevice.BusNumber && device.PortNumbers.SequenceEqual(usbDevice.PortNumbers));

        if (dongleAlreadyExists) return;
        if (!usbDevice.TryOpen()) return;
        
        var usbDeviceClone = usbDevice.Clone();
        
        var device = new Dongle
        {
            UsbDevice = usbDeviceClone
        };

        usbDevice.Close();
        device.UsbDevice.Open();
        
        Dongles.Add(device);
    }
```

**Comment by mcuee** [comment]
@RobertoBiundo 

Can you give PR #192 a try? I can merge the PR if the test is positive.

* #192

**Comment by mcuee** [comment]
Now that PR #192 is merged, I will close this issue.
