### ISSUE TITLE
Usb mutex lock

### ISSUE THREAD

**Issue by vitalijusb85** [LibUsbDotNet/LibUsbDotNet#177]
Hi,  I have two connected devices. Through the loop, I trying open the device and clime interface. So sometimes I getting an error: ../../libusb/os/threads_posix.h:46: usbi_mutex_lock: Assertion `pthread_mutex_lock(mutex) == 0' failed. Aborted.
This error is breaking my app.
What am I doing wrong? 

Thanks for your help.

**Comment by mcuee** [comment]
libusb-1.0.26 should be used. Most likely you have a bug in your application.

**Comment by vitalijusb85** [comment]
Hi, you were right. It was an error in the application in switching different contexts. 
I have one question. Is it possible to set the baud rate? 
Thanks.

**Comment by mcuee** [comment]
> Hi, you were right. It was an error in the application in switching different contexts. I have one question. Is it possible to set the baud rate? Thanks.

There is no such thing as baud rate for USB. If youa are talking about USB to Serial adapters, please do not use libusbdotnet. You need to use other libraries for that.

**Comment by 0wwafa** [comment]
I think libusb is bugged.
I am using libusb-1.0.25.
My program does high speed transfer from usb. Everything works but when at the end I issue the libusb close I get the same error as the OP.
