### ISSUE TITLE
Reading from port byte by byte

### ISSUE THREAD

**Issue by vitalijusb85** [LibUsbDotNet/LibUsbDotNet#178]
Hi, 
in my case, I need to read data from the port byte by byte. I need to analyze the frame.
First, I used the method:
 `public virtual Error Read(byte[] buffer, int offset, int count, int timeout, out int transferLength)`.
I know that my response is 45 bytes. But I want to read the first 6 bytes.  So my buffer size is 6 and offset 0 and count 6.
I get no response from the port. If I set a buffer length of 45 bytes or more it works.
Why doesn't it work?
I use Linux os.

Thanks for your help.

**Comment by mcuee** [comment]
You have set the buffer as 45 bytes in this case. I believe that is the way libusb works.

**Comment by vitalijusb85** [comment]
Thanks for the fast response. It is possible to get from the port buffer length?
