### ISSUE TITLE
New Feature: Event that fires when USB device is connected/disconnected

### ISSUE THREAD

**Issue by brunzefb** [LibUsbDotNet/LibUsbDotNet#179]
It would be nice if the library had some sort of optional background monitoring of all the usb devices in the system.  It would remember them, and fire an event if a new device is added or a device is removed.  The implementation could be a thread that runs at low priority, that that would have to be explicitly started by the user, as not all users are interested in this.

**Comment by mcuee** [comment]
#216 has been merged which add hotplug support for Linux and macOS. I will close this issue for now.

For Windows, libusb still does not support hotplug under Windows.
