### ISSUE TITLE
编译V2分支无法获取USB 存储设备信息

### ISSUE THREAD

**Issue by FreedomPointer** [LibUsbDotNet/LibUsbDotNet#190]
作者，你好！
我编译V2分支后，调用接口仍然获取不到USB 存储盘信息(如”序列号“这样的信息)
还有，必须安装这个软件吗？
但好像只支持windows，如何跨平台呢？
![image](https://user-images.githubusercontent.com/43510930/218460363-9fc0d131-c5c1-4e1f-95dd-5fdb2c8b51d2.png)

**Comment by ChineseK** [comment]
必须安装这个软件

**Comment by mcuee** [comment]
@FreedomPointer 

Please read the following libusb Wiki pages. 
https://github.com/libusb/libusb/wiki/Windows#user-content-Driver_Installation
https://github.com/libusb/libusb/wiki/FAQ

And please DO NOT use libusb/libusbdotnet with USB Mass Storage Device. It is not the right library for your task. 

You will not be able to use it under macOS as there is no way to detach the system driver. 

You have to replace the system USB mass storage driver with a supported driver under Windows.

**Comment by mcuee** [comment]
This is not a libusbdotnet issue and I will close this one.

**Comment by FreedomPointer** [comment]
非常感谢！
@mcuee 
@ChineseK
