### ISSUE TITLE
3.0.102-alpha other memory is corrupt

### ISSUE THREAD

**Issue by OaimIsGnay** [LibUsbDotNet/LibUsbDotNet#218]
3.0.102-alpha

<img width="1836" alt="image" src="https://user-images.githubusercontent.com/58240619/234742095-33ebdfb0-1598-431d-995c-3c12eb3dc270.png">

![image](https://user-images.githubusercontent.com/58240619/234742215-fe24b320-b5b8-4f43-bfd6-4529449e502a.png)

**Comment by mcuee** [comment]
What is the device and OS?

If this is an HID device, please do not use libusbdotnet or libusb under macOS since it will not work. You should use HIDAPI instead.

**Comment by OaimIsGnay** [comment]
> 

windows,  Console error will be reported after running for a while.

**Comment by OaimIsGnay** [comment]
> What is the device and OS?
> 
> If this is an HID device, please do not use libusbdotnet or libusb under macOS since it will not work. You should use HIDAPI instead.
> 
> Reference: https://github.com/libusb/libusb/wiki/FAQ#does-libusb-support-usb-hid-devices

I have resolved the issue and cannot initialize multiple times.

**Comment by zhangxinling2** [comment]
> > 什么是设备和操作系统？
> > 如果这是HID设备，请不要在macOS下使用libusbdotnet或libusb，因为它将无法正常工作。您应该改用 HIDAPI。
> > 参考： https://github.com/libusb/libusb/wiki/FAQ#does-libusb-support-usb-hid-devices
> 
> 我已经解决了这个问题，无法多次初始化。

hello,how do you  resolve this problem
