### ISSUE TITLE
System.NullReferenceException while invoking LibUsbDotNet.LudnMonoLibUsb.MonoUsbDevice.OpenEndpointWriter

### ISSUE THREAD

**Issue by pavanupb** [LibUsbDotNet/LibUsbDotNet#221]
I have an application where I am opening a connection to an instrument from my .Net 6.0 application using the static method `OpenUsbDevice` from the class UsbDevice by passing in the vendor and product Id to UsbDeviceFinder. I am using the same object to push the message by calling the `OpenEndPointWriter((WriteEndpointID)<output_pin>)`. However from time to time I am getting a NullReference exception. Below is the stack trace:

```
 System.NullReferenceException: Object reference not set to an instance of an object.
         at LibUsbDotNet.LudnMonoLibUsb.MonoUsbDevice.OpenEndpointWriter(WriteEndpointID writeEndpointID, EndpointType endpointType)
***** App_Stack trace *******  
```

In my logs I am able to see that the `IsPortOpen` is true and was able to see the information as well from the UsbDevice object at the time of exception.

`Version: LibUsbDotNet 2.2.29`

`OS: Raspi OS`

I am running my application inside a docker container on a Raspberry Pi 4 machine

Please let me know If I am doing something wrong

**Comment by mcuee** [comment]
Can you try the latest v2 git branch? 2.2.29 has quite some issues.

**Comment by mcuee** [comment]
Or you may want to try the latest master branch (V3), some changes may be required if you switch to V3.

**Comment by pavanupb** [comment]
> Can you try the latest v2 git branch? 2.2.29 has quite some issues.

@mcuee Thanks for the suggestion. Could you please let me know which version in nuget are related to v2. I can see a list of alpha versions in nuget gallery

**Comment by pavanupb** [comment]
@mcuee Is the artifacts from v2 branch pushed to nuget gallery?

**Comment by pavanupb** [comment]
Thanks @mcuee . Are there any plans to release the v2 version to the nuget in near future?

**Comment by mcuee** [comment]
> Thanks @mcuee . Are there any plans to release the v2 version to the nuget in near future?

We have to wait @qmfrederik to do that.

**Comment by mcuee** [comment]
> [@mcuee](https://github.com/mcuee) [@sdijoseph](https://github.com/sdijoseph) When can we expect a new official release of v3 and publishing the package to nuget?. I saw the post: [#266](https://github.com/LibUsbDotNet/LibUsbDotNet/issues/266). Currently I am using 3.0.154-alpha.

Have you tried the latest version?
https://www.nuget.org/packages/LibUsbDotNet/#versions-body-tab
https://www.nuget.org/packages/LibUsbDotNet/3.0.167-alpha
