### ISSUE TITLE
ResetDevice（） error

### ISSUE THREAD

**Issue by nlcc96131415** [LibUsbDotNet/LibUsbDotNet#222]
The following error appear when invoke ResetDevice() 

System.AccessViolationException:“Attempted to read or write protected memory. This is often an indication that other memory is corrupt.”

**Comment by mcuee** [comment]
You need to provide more details, like the OS, the device info, etc.

**Comment by nlcc96131415** [comment]
The device is a moto driver board with a cortex-m0 MCU and no OS.



---Original---
From: ***@***.***&gt;
Date: Thu, Jul 27, 2023 16:37 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [LibUsbDotNet/LibUsbDotNet] ResetDevice（） error (Issue #222)




 
You need to provide more details, like the OS, the device info, etc.

**Comment by mcuee** [comment]
In general you do not need to call ResetDevice unless your device is buggy or you are updating FW.

And after that, your device handle is usually no longer valud and you need to go through the process of finding the device again.
