### ISSUE TITLE
3.0.102-alpha memory error

### ISSUE THREAD

**Issue by zhangxinling2** [LibUsbDotNet/LibUsbDotNet#223]
![image](https://github.com/LibUsbDotNet/LibUsbDotNet/assets/44797748/ae2ed9d2-7193-4645-aea9-6eea8b54a145)
my problem like that,but something is different
This error occurs when I finish a write, but if I add a delay of a few seconds at the end it doesn't appear，this is why，how can i solve

**Comment by mcuee** [comment]
Please do not use libusbdotnet with USB HID device.

Please use HIDAPI and its dotnet bindings.
https://github.com/libusb/hidapi/wiki

**Comment by mcuee** [comment]
BTW, your read endpoint (IN Endpoint) should be 0x81 and not 0x01.

**Comment by zhangxinling2** [comment]
<img width="946" alt="image" src="https://github.com/LibUsbDotNet/LibUsbDotNet/assets/44797748/3a472d2c-3b91-4225-a182-4fe73d78cffc">
I successfully operated with USB using libusb via QT, but now I need to use C# to operate on usb。
In fact, this  write data successfully, I finded changes to USB devices, but an memory error occurs after the write succeeds.
Strangely, I don't get this error by adding a sleep after a successful write
I think libusbdotnet worked, but don't know why the error happened

**Comment by zhangxinling2** [comment]
> BTW, your read endpoint (IN Endpoint) should be 0x81 and not 0x01.

![image](https://github.com/LibUsbDotNet/LibUsbDotNet/assets/44797748/a111e404-1126-4d42-b9b1-bd189db2d19d)
I successfully operated with USB using libusb via QT, but now I need to use C# to operate on usb。 In fact, this write data successfully, I finded changes to USB devices, but an memory error occurs after the write succeeds. Strangely, I don't get this error by adding a sleep after a successful write I think libusbdotnet worked, but don't know why the error happened

**Comment by mcuee** [comment]
Have you tried git master and not 3.0.102-alpha?

**Comment by zhangxinling2** [comment]
> Have you tried git master and not 3.0.102-alpha?

I use 
IUsbDevice usbDevice = (UsbDevice)context. Find(MyUsbFinder); 
instead of
 var usbDeviceCollection = context. List();
 var usbDevice = usbDeviceCollection.FirstOrDefault(d => d.ProductId == pid && d.VendorId == vid); 
This error no longer occurs.
