### ISSUE TITLE
System.DllNotFoundException:“Unable to load DLL 'libusb-1.0' or one of its dependencies

### ISSUE THREAD

**Issue by huster-songtao** [LibUsbDotNet/LibUsbDotNet#227]
System.DllNotFoundException:“Unable to load DLL 'libusb-1.0' or one of its dependencies: 找不到指定的模块。 (0x8007007E)”

Unable to load DLL 'libusb-1.0' or one of its dependencies: 找不到指定的模块。 (0x8007007E)

   在 LibUsbDotNet.NativeMethods.Init(IntPtr& ctx)
   在 LibUsbDotNet.LibUsb.UsbContext..ctor() 在 C:\Users\Steven\Downloads\LibUsbDotNet-master\LibUsbDotNet-master\src\LibUsbDotNet\LibUsb\UsbContext.cs 中: 第 87 line
   在 Examples.ReadPolling.Main(String[] args) 在 C:\Users\Steven\Downloads\LibUsbDotNet-master\LibUsbDotNet-master\src\Examples\Read.Only\ReadOnly.cs 中: 第 23 line

**Comment by mcuee** [comment]
You have to have `libusb-1.0.dll` in your system.

**Comment by huster-songtao** [comment]
![20230921173536](https://github.com/LibUsbDotNet/LibUsbDotNet/assets/94954133/a7a42424-6b15-49b4-914c-ad917659989a)

```
<Content Include="$(VCPKG_ROOT)/installed/x64-windows/bin/libusb-1.0.dll">
      <PackagePath>runtimes/win-x64/native/%(Filename)%(Extension)</PackagePath>
      <Pack>true</Pack>
    </Content>
```

To add the vcpkg directory to the environment variable: 
Environment variable name: VCPKG_ROOT 
Value: The installation directory of vcpkg, my path is E:\vcpkg\vcpkg

I have libusb-1.0.dll in E:\vcpkg\vcpkg\installed\x64-windows\bin

so, I have libusb-1.0.dll  in $(VCPKG_ROOT)/installed/x64-windows/bin/libusb-1.0.dll

**Comment by mcuee** [comment]
That will not work. vcpkg will let Visual Studio find it but not your application. 

You can put `libusb-1.0.dll` in the same directory of your exe file.

**Comment by huster-songtao** [comment]
![20230921175013](https://github.com/LibUsbDotNet/LibUsbDotNet/assets/94954133/4e303c42-e23c-4683-a631-eb2e16fca719)

To view a file's properties, right-click on the file and select "Properties" to open the Properties window below. 
![20230921175305](https://github.com/LibUsbDotNet/LibUsbDotNet/assets/94954133/5b09dc8d-3449-4164-ba98-5683af1038b7)

the full path 'C:\installed\arm64-windows\bin\libusb-1.0.dll'
$(VCPKG_ROOT) is 'C:\' but not 'E:\vcpkg\vcpkg'

I have no idea for $(VCPKG_ROOT)
I will try later

**Comment by mcuee** [comment]
Just ignore that. Put libusb-1.0.dll in the same directory as your exe file.
