### ISSUE TITLE
Unable to load DLL 'libusb-1.0' or one of its dependencies: 找不到指定的模块。 

### ISSUE THREAD

**Issue by huster-songtao** [LibUsbDotNet/LibUsbDotNet#228]
在 LibUsbDotNet.NativeMethods.Init(IntPtr& ctx)
   在 LibUsbDotNet.LibUsb.UsbContext..ctor() 在 C:\Users\Steven\Downloads\LibUsbDotNet-master\LibUsbDotNet-master\src\LibUsbDotNet\LibUsb\UsbContext.cs 中: 第 100 line
   在 Examples.ReadPolling.Main(String[] args) 在 C:\Users\Steven\Downloads\LibUsbDotNet-master\LibUsbDotNet-master\src\Examples\Read.Only\ReadOnly.cs 中: 第 27 line

**Comment by mcuee** [comment]
Please do not create a new duplicate issue.

I have already answered in the other issue.
https://github.com/LibUsbDotNet/LibUsbDotNet/issues/227

**Comment by mcuee** [comment]
Take note this github is not for technical support, rather it is for reporting issues of libusbdotnet.

**Comment by mcuee** [comment]
Please also read the Wiki and FAQ first before asking questions.
* https://github.com/LibUsbDotNet/LibUsbDotNet/issues/143
