### ISSUE TITLE
LibUsbdotnet INF File Device Manager Code10 Error

### ISSUE THREAD

**Issue by serhanyilmaz** [LibUsbDotNet/LibUsbDotNet#23]
Firstly of all Hello,

 I have LibUsbDotNet source code.

 First case:  
 I prepare the INF file for the device we have produced With **LibUsbDotNet  INFWizard**.
If my device has a **FIFO size of 64 bytes**, I get the following code when I load the INF file to the computer.
(Code  received via USBTreeView tool.)
+++++++++++++++++ Device Information ++++++++++++++++++

---------------- Connection Information ---------------

Current Config Value : 0x01
**Number Of Open Pipes : 0x02 (2)**
Device Bus Speed : 0x01 (Full-Speed)
**Pipe0ScheduleOffset : 0x00 (0)
Pipe1ScheduleOffset : 0x00 (0)**
---------------------- Device Descriptor ----------------------

bcdUSB : 0x110 (USB Version 1.10)
bDeviceClass : 0xFF (Vendor Specific)
bDeviceSubClass : 0x00
bDeviceProtocol : 0x00
bMaxPacketSize0 : 0x40 (64 bytes)
bcdDevice : 0x0100

---------------- Interface Descriptor -----------------

bNumEndpoints : 0x02 (2 Endpoints)
bInterfaceClass : 0xFF (Vendor Specific)
bInterfaceSubClass : 0x00
bInterfaceProtocol : 0x00

----------------- Endpoint Descriptor -----------------
bmAttributes             : 0x02 (TransferType=Bulk)
**wMaxPacketSize : 0x0040 (64 bytes)**

----------------- Endpoint Descriptor -----------------

bmAttributes : 0x02 (TransferType=Bulk)
**wMaxPacketSize : 0x0040 (64 bytes)**

Second case:
 I prepare the INF file for the device we have produced With **LibusbK -inf-wizard.exe**.
If my device has a **FIFO size of 1024 bytes**, I get the following code when I load the INF file to the computer.
(Code received via USBTreeView tool.)
+++++++++++++++++ Device Information ++++++++++++++++++

        ---------------- Connection Information ---------------

Current Config Value     : 0x00
**Number Of Open Pipes     : 0x00 (0)**
Device Bus Speed         : 0x01 (Full-Speed)

    ---------------------- Device Descriptor ----------------------

bcdUSB                   : 0x200 (USB Version 2.00)
bDeviceClass             : 0x02 (Communications and CDC Control)
bDeviceSubClass          : 0x02
bDeviceProtocol          : 0x01 (AT Commands defined by ITU-T V.250 etc)
bMaxPacketSize0          : 0x40 (64 bytes)
bcdDevice                : 0x0200

        ---------------- Interface Descriptor -----------------

bNumEndpoints            : 0x02 (2 Endpoints)
bInterfaceClass          : 0x02 (Communications and CDC Control)
bInterfaceSubClass       : 0x02 (Abstract Control Model)
bInterfaceProtocol       : 0x01 (AT Commands defined by ITU-T V.250 etc)

        ----------------- Endpoint Descriptor -----------------

bmAttributes             : 0x02 (TransferType=Bulk)
**wMaxPacketSize           : 0x0400 (1024 bytes)**

        ----------------- Endpoint Descriptor -----------------
bmAttributes             : 0x02 (TransferType=Bulk)
**wMaxPacketSize           : 0x0400 (1024 bytes)**

**Comment by qmfrederik** [comment]
Thank you for your issue and sorry for the time it took to reply.

Here are some thoughts:
1. There isn't really anyone actively working on the INF wizard, and it's very likely we'll remove it alltogether from LibUsbDotNet. A better option is to use [Zadig](https://zadig.akeo.ie/). Can you give Zadig a try?
2. I'm not sure what the actual issues you are reporting here. Can you let me know what happened and what you expected to happen?
3. Because this is old, I'm going to close this issue for now. Feel free to reopen, though.
