### ISSUE TITLE
No more interfaces found 

### ISSUE THREAD

**Issue by Mrf2233** [LibUsbDotNet/LibUsbDotNet#238]
I used TestLibUsb_win from libusb and Test_Info from LibUsbDotNet. I found that the number of interfaces is different.
![QQ截图20240130120510](https://github.com/LibUsbDotNet/LibUsbDotNet/assets/57277431/30b6a817-4eab-4a8f-9c29-28402d32e672)

**Comment by mcuee** [comment]
The device has different configurations.
