### ISSUE TITLE
MonoApiError:MonoApiError:SubmitTransfer Ep 0x02

### ISSUE THREAD

**Issue by Gituhg** [LibUsbDotNet/LibUsbDotNet#240]
Hi all,

I'm developing a service using .Net core, LibUSBDotNet (2.2.29), and Linux (openEuler-22.03-LTS-SP3-x86_64). Has anyone encountered this error when calling the write function:

Specific line of code from the sample code：
epWriter = usbDevice.OpenEndpointWriter(WriteEndpointID.Ep02);
Error:
MonoApiError:MonoApiError:SubmitTransfer Ep 0x02

**Comment by mcuee** [comment]
You have to know the device communication protocol in order to use libusb/libusbdotnet.
