### ISSUE TITLE
Missing nuget package libusb.common

### ISSUE THREAD

**Issue by MaitreDede** [LibUsbDotNet/LibUsbDotNet#25]
Hi,
With the latest available version on nuget `2.2.9-r21`, you added a dependency to the package `LibUsb.Common`, but nuget returns 404.
Also there is https://github.com/LibUsbDotNet/LibUsbDotNet/issues/21...

Thanks :)

**Comment by TAGC** [comment]
Yeah I pointed that out a month ago [here](https://github.com/LibUsbDotNet/LibUsbDotNet/pull/20). No response.

**Comment by qmfrederik** [comment]
It should be online now: https://www.nuget.org/packages/LibUsb.Common/
