### ISSUE TITLE
Win32Error:PipeTransferSubmit error -16367 on specific AMD CPUs

### ISSUE THREAD

**Issue by micler00** [LibUsbDotNet/LibUsbDotNet#252]
Hi, I am currently facing issues with the libusb-interface on specific AMD CPUs (Ryzen 7 5700, Threadripper PRO 5945WX) resulting in Win32Error:PipeTransferSubmit (error code -16367). I am using the libusb-win32 version 1.2.6.0 driver, LibUsbDotNet 2.2.29, .NET 8.0 and Windows 10:
```
using LibUsbDotNet;

var usbRegistry = UsbDevice.AllLibUsbDevices.First(device => device.Vid == 5485);
usbRegistry.Open(out var usbDevice);

var success = ((IUsbDevice)usbDevice).ClaimInterface(0); //This usually returns true, but false for AMD Ryzen 7 5700 and Threadripper
var writer = usbDevice.OpenEndpointWriter(WriteEndpointID.Ep02);
var errorCode = writer.Write(new byte[1]{0x01}, 1000, out var writtenBytes);  //Error for AMD Ryzen 7 5700 and Threadripper, writtenBytes is 0
```

The code is working fine with different Intel CPUs, a Ryzen 3 3100 and a Ryzen 5 5600. 
I was also investigating the device using Usb Device Tree Viewer, where anything looks normal.

Is there any known issue regarding specific AMD CPUs? Any ideas what the problem could be?
Thanks in advance!

**Comment by mcuee** [comment]
The outdated driver may be the problem.

You should upgrade your libusb-win32 driver to the latest release version.
https://github.com/mcuee/libusb-win32/releases/tag/release_1.4.0.0

You can download Zadig 2.9 release to install libusb-win32 device driver (libusb0.sys) 1.4.0.0 version.
https://github.com/pbatard/libwdi/releases/tag/v1.5.1

**Comment by micler00** [comment]
I could resolve the issue. It had nothing to do with LibUsbDotNet or the driver. For info if someone comes across this:
It seems that this specific type of AMD USB host controller did not support the endpoint configuration (1 x BULK-IN and 1 x BULK-OUT) of my device which is very strange to me since it is totally compatible with the standard. Also, the device was working on all sorts of different CPUs for many years now without any issue.
Anyway, changing the endpoint configuration to one Interrupt- and one Bulk-endpoint solved it for me.
