### ISSUE TITLE
Unable to get mount location

### ISSUE THREAD

**Issue by yyhLogin** [LibUsbDotNet/LibUsbDotNet#255]
On Linux Unable to get mount location

**Comment by yyhLogin** [comment]
using UsbContext context = new UsbContext();
context.RegisterHotPlug();
DeviceEventArgs 
If a USB flash drive is connected, the directory mounted on the USB flash drive cannot be obtained.

**Comment by mcuee** [comment]
libusbdotnet (or libusb) is not the correct library for your use case.

**Comment by mcuee** [comment]
You may want to ask in other place like StackOverflow.
