### ISSUE TITLE
2.2.29: libusb-1.0.dll not found (2.2.8 works)

### ISSUE THREAD

**Issue by Xenoage** [LibUsbDotNet/LibUsbDotNet#67]
I updated from LibUsbDotNet 2.2.8 to 2.2.29
When using libusb (`UsbDevice.ForceLibUsbWinBack = true;`) and trying to open an USB device (`UsbDevice.OpenUsbDevice(...)`) an Exception is thrown:

`System.DllNotFoundException: libusb-1.0.dll not found. If this is a 64bit operating system, ensure that the 64bit version of libusb-1.0.dll exists in the '\Windows\System32' directory. ---> System.DllNotFoundException: Die DLL "libusb-1.0": Das angegebene Modul wurde nicht gefunden. (Ausnahme von HRESULT: 0x8007007E) kann nicht geladen werden.`

libusb-1.0.dll is in the same directory as the application exe. Also placing it in the other directories does not help. Since it is working again when I downgrade to version 2.2.8, I guess it is a bug in one of the latest updates.

**Comment by enbyted** [comment]
I have te same issue. The problem appears on 2.2.18 and newer, but not on 2.2.8.

**Comment by Ledrunning** [comment]
I have the same problem with MonoUsbSessionHandle.

> | $exception | {"libusb-1.0.dll not found. If this is a 64bit operating system, ensure that the 64bit version of libusb-1.0.dll exists in the '\\Windows\\System32' directory."} | System.DllNotFoundException

**Comment by MelbourneDeveloper** [comment]
Actually, I edited the Read.Write sample and unless I copy the DLL to the output folder, I always get this error. What's the deal? What are we supposed to do to make sure the C DLL gets deployed? Does it need to be installed on the target machine or something?

**Comment by Kleinrotti** [comment]
Got it working by removing the file extension. From libusb-1.0.dll to libusb-1.0

**Comment by nosmokingbandit** [comment]
I have this problem using the latest pre-release 3.0.48. It works as expected in one project, but not another. I can't seem to determine what the cause is.

**Comment by mcgoober** [comment]
I found that with pre-release v3.0.48 you have to build your project in either x64 or x86. 'Any CPU' doesn't work and gives the error above.

**Comment by mcuee** [comment]
Please try the latest main git and the latest v2 branch. It should work.
