### ISSUE TITLE
MonoApiError:MonoApiError:SubmitTransfer Ep 0x01  -1:ErrorIO:Input/output error

### ISSUE THREAD

**Issue by gqbgqb** [LibUsbDotNet/LibUsbDotNet#69]
Hi all,

I'm developing a service using **.Net core, LibUSBDotNet (2.2.29), and Linux (Ubuntu 18.04)**. Has anyone encountered this error when calling the write function: 

**Specific line of code from the sample code**
`ec = writer.Write(Encoding.Default.GetBytes(cmdLine), 2000, out bytesWritten);
if (ec != ErrorCode.None) throw new Exception(UsbDevice.LastErrorString);`

**Error:**
`MonoApiError:MonoApiError:SubmitTransfer Ep 0x01  -1:ErrorIO:Input/output error`

I've confirmed that I'm using the correct End point (using this command: sudo lsusb -v -d vendorid:productid). I've also given the correct permission for the device (using udev rules). 

USB INFO: 
Bus 001 Device 007: ID 0828:0131 Sato Corp. 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x0828 Sato Corp.
  idProduct          0x0131 
  bcdDevice            2.16
  iManufacturer           1 SATO CORPORATION
  iProduct                2 SATO PW208mNX
  iSerial                 3 TESB0081
  bNumConfigurations      1
OTG Descriptor:
  bLength                 3
  bDescriptorType         9
  bmAttributes         0x03
    SRP (Session Request Protocol)
    HNP (Host Negotiation Protocol)
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           35
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower                2mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         7 Printer
      bInterfaceSubClass      1 Printer
      bInterfaceProtocol      2 Bidirectional
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
Device Qualifier (for other device speed):
  bLength                10
  bDescriptorType         6
  bcdUSB               2.00
  bDeviceClass            7 Printer
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  bNumConfigurations      1
Device Status:     0x0001
  Self Powered

I was hoping someone who has more experience in implementing the library can help me with suggestions on how to solve this.

Thanks in advance ,
Glenn

**Comment by YfavreUnige** [comment]
Hi Glenn,
I've got exactly the same issue on a MonoUsbEndpointWriter.
Did you solve the issue on your side and if yes could you share it ?
Thanks in advance ,
Yannick

**Comment by codeoflin** [comment]
I've got exactly the same issue too

**Comment by mcuee** [comment]
You have to know the communication protocol of the device in order to use libusb and libusbdotnet. This usually means that the device does not understand the commands sent to the device.

**Comment by AsylbekA** [comment]
has anyone solved this problem? or is there an alternative option?
