### ISSUE TITLE
File Not Found Exception for UsbDevice.AllDevices;

### ISSUE THREAD

**Issue by eriadel** [LibUsbDotNet/LibUsbDotNet#70]
Hi there,

I'm trying to run LibUSBDotNet in version 2.2.8, but
I get File Not Found Exception in my UWP / RuntimeComponent application.

Do you guys know what's missing here ?

StackTrace	
LibUsbDotNet.WinUsb.WinUsbRegistry.WinUsbRegistryCallBack(IntPtr deviceInfoSet, Int32 deviceIndex, SP_DEVINFO_DATA& deviceInfoData, Object classEnumeratorCallbackParam1)

LibUsbDotNet.Internal.SetupApi.EnumClassDevs(String enumerator, DICFG flags, ClassEnumeratorDelegate classEnumeratorCallback, Object classEnumeratorCallbackParam1)

LibUsbDotNet.WinUsb.WinUsbRegistry.get_DeviceList()LibUsbDotNet.UsbDevice.get_AllWinUsbDevices()

LibUsbDotNet.UsbDevice.get_AllDevices()

CameraManager.DeviceDetector.Detect()

Thank you in advance, 
Carl

**Comment by mcuee** [comment]
I tend to believe UWP will not work.
