### ISSUE TITLE
AllDevices Yields No Devices

### ISSUE THREAD

**Issue by MelbourneDeveloper** [LibUsbDotNet/LibUsbDotNet#74]
Version: 2.2.29

![image](https://user-images.githubusercontent.com/16697547/49693201-77fa8700-fbc0-11e8-8c0b-9668283a23d3.png)

**Comment by seuzht** [comment]
I also met similar problem. But usually when I set a breakpoint to debug my code, the device (even if exists) would suddenly change to null.

**Comment by MelbourneDeveloper** [comment]
@seuzht the NuGets are not in a working state. I had to grab an alpha version of a new release. Please follow the issue here: https://github.com/LibUsbDotNet/LibUsbDotNet/issues/73#issuecomment-445978402  . I have added a working sample in that thread.

**Comment by raulhaag** [comment]
@MelbourneDeveloper  the example works well but i have problem to release all resources, it throws
```
 System.AccessViolationException: Intento de leer o escribir en la memoria protegida. A menudo, esto indica que hay otra memoria dañada.
   en LibUsbDotNet.NativeMethods.UnrefDevice(IntPtr dev)
   en LibUsbDotNet.Device.ReleaseHandle()
   en System.Runtime.InteropServices.SafeHandle.InternalFinalize()
   en System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
   en System.Runtime.InteropServices.SafeHandle.Finalize()
```
at end or when retry. Any hint?  i tried 
```
usbDevice.ReleaseInterface(usbDevice.Configs[0].Interfaces[0].Number);
usbDevice.Close();
```

**Comment by MelbourneDeveloper** [comment]
@raulhaag sorry I don't have any hints. The library has undergone some major changes. I think you will have to try to fix the bug and then submit a pull request.

**Comment by MelbourneDeveloper** [comment]
@raulhaag , this seems like a separate bug. Do you want to document this up completely for the LibUsbDotNet team and create a new issue? I'd like to close this ticket seeing technically it is possible to connect.

**Comment by raulhaag** [comment]
@MelbourneDeveloper no problem close it and i go to make a new issue more detailed and with a example proyect
