### ISSUE TITLE
DeviceNotify support on macOS (or at least warn there is no support!)

### ISSUE THREAD

**Issue by aroman** [LibUsbDotNet/LibUsbDotNet#79]
It seems that DeviceNotify only works on Windows or Linux (not macOS). If running on macOS, the library tries to load Windows-only DLLs, and can cause strange behavior (infinite hang in my case).

The library should at least detect if the OS is macOS/darwin and raise an error/log a warning to the user instead of falling back to broken behavior.

**Comment by mcuee** [comment]
I believe this has never been implemented under macOS. On the other hand now that hotplug is available under libusb for Linux/MacOS (not yet on Windows), probably this can be improved.

**Comment by mcuee** [comment]
Please also refer to this one.
https://github.com/LibUsbDotNet/LibUsbDotNet/issues/32

**Comment by mcuee** [comment]
The proper way is to use libusb hotplug API. Please refer to #32 for further discussions.
