### ISSUE TITLE
NativeMethods Dependency Injection

### ISSUE THREAD

**Issue by MelbourneDeveloper** [LibUsbDotNet/LibUsbDotNet#81]
When you first pull the repo, it doesn't compile because there are #ifs everywhere.

One approach to solving this issue could be to split the platform specific code in NativeMethods out in to separate libraries that are compiled for that platform, and an interface called INativeMethods could be introduced for dependency injection.

It's a little more maintenance in terms of DLLs etc. but it means that all the projects would compile out of the box without having to run conditional compilation symbols on.

Thoughts?

**Comment by mcuee** [comment]
Now there is no building issue for both the master branch and v2 branch. I will close this one.
