### ISSUE TITLE
Device.Net Implementation

### ISSUE THREAD

**Issue by MelbourneDeveloper** [LibUsbDotNet/LibUsbDotNet#82]
[Device.Net](https://github.com/MelbourneDeveloper/Device.Net) is a base library for USB, and Hid devices. It's based around a very simple interface called [IDevice](https://github.com/MelbourneDeveloper/Device.Net/wiki/IDevice). The basic purpose of this interface is to be able to use any USB, or Hid library to communicate with connected devices across multiple platforms. The major tested platforms are Android, Windows, and UWP, but LibUsbDotNet would bring Linux and MacOS which would be a huge win.

_Update: I have created a [library](https://github.com/MelbourneDeveloper/Device.Net/tree/master/src/Device.Net.LibUsb) which bridges LibUsbDotNet and Device.Net. It's been tested and runs on MacOS. The NuGet is [here](https://www.nuget.org/packages/Device.Net.LibUsb/). I would still prefer to work with you guys and come to a middle ground so that LibUsbDotNet could have a Device.Net implementation if possible._ 

There is another interface called [IDeviceFactory](https://github.com/MelbourneDeveloper/Device.Net/blob/master/src/Device.Net/IDeviceFactory.cs) which is a bare bones device enumeration interface. When implemented, functionality is automatically harnessed to listen for device connections and disconnections. The long and short of it is that with this implementation, any project using LibUsbDotNet automatically gets code that will automate the messy business of handling plugging and unplugging the device.

I've already made these changes in my [fork](https://github.com/MelbourneDeveloper/LibUsbDotNet/tree/DeviceNet). I have not submitted this as a pull request, because I'd rather put this up as a talking point before I propose any changes to your library. I also need to clean a few things up  to minimize changes to your library and test thoroughly.

The changes to the class [UsbDevice ](https://github.com/MelbourneDeveloper/LibUsbDotNet/blob/DeviceNet/src/LibUsbDotNet/LibUsb/UsbDevice.cs) are minimal, but for a small change to how your users would use the class - i.e. using task based async methods instead of synchronous methods, they would get full cross platform compatibility and all the trimmings of having device listeners on all platforms.

Here's an example of what LibUsbDotNet would gain from implementation. This code is shared across Windows, UWP, and Android exactly as is. You can see this code working with LibUsbDotNet directly [here](https://github.com/MelbourneDeveloper/LibUsbDotNet/blob/DeviceNet/src/Examples/Read.Write/TrezorExample.cs).

````cs
    internal class TrezorExample : IDisposable
    {
        #region Fields
        //Define the types of devices to search for. This particular device can be connected to via USB, or Hid
        private readonly List<FilterDeviceDefinition> _DeviceDefinitions = new List<FilterDeviceDefinition>
        {
            new FilterDeviceDefinition{ DeviceType= DeviceType.Hid, VendorId= 0x534C, ProductId=0x0001, Label="Trezor One Firmware 1.6.x", UsagePage=65280 },
            new FilterDeviceDefinition{ DeviceType= DeviceType.Usb, VendorId= 0x534C, ProductId=0x0001, Label="Trezor One Firmware 1.6.x (Android Only)" },
            new FilterDeviceDefinition{ DeviceType= DeviceType.Usb, VendorId= 0x1209, ProductId=0x53C1, Label="Trezor One Firmware 1.7.x" },
            new FilterDeviceDefinition{ DeviceType= DeviceType.Usb, VendorId= 0x1209, ProductId=0x53C0, Label="Model T" }
        };
        #endregion

        #region Events
        public event EventHandler TrezorInitialized;
        public event EventHandler TrezorDisconnected;
        #endregion

        #region Public Properties
        public IDevice TrezorDevice { get; private set; }
        public DeviceListener DeviceListener { get; private set; }
        #endregion

        #region Event Handlers
        private void DevicePoller_DeviceInitialized(object sender, DeviceEventArgs e)
        {
            TrezorDevice = e.Device;
            TrezorInitialized?.Invoke(this, new EventArgs());
        }

        private void DevicePoller_DeviceDisconnected(object sender, DeviceEventArgs e)
        {
            TrezorDevice = null;
            TrezorDisconnected?.Invoke(this, new EventArgs());
        }
        #endregion

        #region Public Methods
        public void StartListening()
        {
            TrezorDevice?.Dispose();
            DeviceListener = new DeviceListener(_DeviceDefinitions, 3000);
            DeviceListener.DeviceDisconnected += DevicePoller_DeviceDisconnected;
            DeviceListener.DeviceInitialized += DevicePoller_DeviceInitialized;
        }

        public async Task InitializeTrezorAsync()
        {
            //Get the first available device and connect to it
            var devices = await DeviceManager.Current.GetDevices(_DeviceDefinitions);
            TrezorDevice = devices.FirstOrDefault();
            await TrezorDevice.InitializeAsync();
        }

        public async Task<byte[]> WriteAndReadFromDeviceAsync()
        {
            //Create a buffer with 3 bytes (initialize)
            var writeBuffer = new byte[64];
            writeBuffer[0] = 0x3f;
            writeBuffer[1] = 0x23;
            writeBuffer[2] = 0x23;

            //Write the data to the device
            return await TrezorDevice.WriteAndReadAsync(writeBuffer);
        }

        public void Dispose()
        {
            TrezorDevice?.Dispose();
        }
        #endregion
}
````

Console app usage:

````cs
    internal class ReadWrite
    {
        #region Fields
        private static TrezorExample _DeviceConnectionExample = new TrezorExample();
        #endregion

        #region Main
        private static void Main(string[] args)
        {
            //Register the factory for creating LibUsbDotNet devices. This only needs to be done once.
            UsbDeviceFactory.Register();

            _DeviceConnectionExample.TrezorInitialized += _DeviceConnectionExample_TrezorInitialized;
            _DeviceConnectionExample.TrezorDisconnected += _DeviceConnectionExample_TrezorDisconnected;

            Go(Menu());

            new ManualResetEvent(false).WaitOne();
        }

        private static async Task Go(int menuOption)
        {
            switch (menuOption)
            {
                case 1:
                    try
                    {
                        await _DeviceConnectionExample.InitializeTrezorAsync();
                        await DisplayDataAsync();
                        _DeviceConnectionExample.Dispose();
                    }
                    catch (Exception ex)
                    {
                        Console.Clear();
                        Console.WriteLine(ex.ToString());
                    }
                    Console.ReadKey();
                    break;
                case 2:
                    Console.Clear();
                    DisplayWaitMessage();
                    _DeviceConnectionExample.StartListening();
                    break;
            }
        }
        #endregion

        #region Event Handlers
        private static void _DeviceConnectionExample_TrezorDisconnected(object sender, EventArgs e)
        {
            Console.Clear();
            Console.WriteLine("Disconnnected.");
            DisplayWaitMessage();
        }

        private static async void _DeviceConnectionExample_TrezorInitialized(object sender, EventArgs e)
        {
            try
            {
                Console.Clear();
                await DisplayDataAsync();
            }
            catch (Exception ex)
            {
                Console.Clear();
                Console.WriteLine(ex.ToString());
            }
        }
        #endregion

        #region Private Methods
        private static int Menu()
        {
            while (true)
            {
                Console.Clear();
                Console.WriteLine("Console sample. This sample demonstrates either writing to the first found connected device, or listening for a device and then writing to it. If you listen for the device, you will be able to connect and disconnect multiple times. This represents how users may actually use the device.");
                Console.WriteLine();
                Console.WriteLine("1. Write To Connected Device");
                Console.WriteLine("2. Listen For Device");
                var consoleKey = Console.ReadKey();
                if (consoleKey.KeyChar == '1') return 1;
                if (consoleKey.KeyChar == '2') return 2;
            }
        }

        private static async Task DisplayDataAsync()
        {
            var bytes = await _DeviceConnectionExample.WriteAndReadFromDeviceAsync();
            Console.Clear();
            Console.WriteLine("Device connected. Output:");
            DisplayData(bytes);
        }

        private static void DisplayData(byte[] readBuffer)
        {
            Console.WriteLine(string.Join(" ", readBuffer));
            Console.ReadKey();
        }

        private static void DisplayWaitMessage()
        {
            Console.WriteLine("Waiting for device to be plugged in...");
        }
        #endregion
    }
````

These are the other sample libraries that share the code:
[UWP](https://github.com/MelbourneDeveloper/Device.Net/tree/master/src/Usb.Net.UWP.Sample)
[Windows](https://github.com/MelbourneDeveloper/Device.Net/tree/master/src/Usb.Net.WindowsSample)
[Android](https://github.com/MelbourneDeveloper/Device.Net/tree/master/src/Usb.Net.AndroidSample)

Some screenshots:

![image](https://user-images.githubusercontent.com/16697547/51797543-bffd6800-2259-11e9-979b-db44f932ace1.png)

![image](https://user-images.githubusercontent.com/16697547/51797545-cab7fd00-2259-11e9-9ae0-f8f22509662d.png)

![image](https://user-images.githubusercontent.com/16697547/51797551-dc99a000-2259-11e9-908c-22a82e242a15.png)

![image](https://user-images.githubusercontent.com/16697547/51797557-e7eccb80-2259-11e9-8e85-7008ccae3651.png)

This is the same code, but with a different library on UWP:
![image](https://user-images.githubusercontent.com/16697547/51797618-cb04c800-225a-11e9-826d-8bbd019c5bf5.png)

You can see the full sample [here](https://github.com/MelbourneDeveloper/LibUsbDotNet/tree/DeviceNet/src/Examples/Read.Write).

Feel free to send feedback my way, and I'll continue to work on minimizing changes to the library etc. I hope this is something that would be useful for your library. I will submit a pull request when I feel like I've done everything I can do stabilize this change.

@andrasfuchs @qmfrederik @libusbdotnet

**Comment by MelbourneDeveloper** [comment]
@qmfrederik thoughts?

**Comment by doug62** [comment]
@MelbourneDeveloper  - Writing to thank you for your contribution, I'm currently researching how to recompile the nuget to accomodate arm32....

**Comment by mcuee** [comment]
Device.Net looks like a nice project.
Unfortunately I can not build it under Linux and macOS. If there is a simple guide, I can test it as well.

**Comment by mcuee** [comment]
Device.Net is a seperate project and now the development seems to stop. So I will close this issue.
