### ISSUE TITLE
Failed Read

### ISSUE THREAD

**Issue by Proclivis** [LibUsbDotNet/LibUsbDotNet#84]
I am seeing a Read failure on a high speed bulk EP on Ubuntu 16 and LibUsbDotNet 2.2.8 or 2.2.29 and standard 2.0 or 2.1.

The application has a pattern like Write-Read-Read-Read Write-Read-Read-Read . The first read intermittently fails by returning len of 0 and the buffer may or may not have the data.

Spying on the physical bus with a Beagle shows that the data of the failed Read actually transferred. In those cases where len is 0 and the buffer has data, it matches the Beagle.

This means some bytes just go missing in the application, and it fails, and there is no way to retry, because the next Read gets the next packet of data.

Adding a Thread.Sleep(4) between Write-Read fixes it.

The Sleep changes the characteristic of the data sent, in that the probability of a single byte return (most often failure) goes way down. This is because the buffering in the FX3 device has more time to push bytes. However, there still are some single bytes on the second and third Read and these are not having a problem.

Once the sleep is added, if I monitor traffic, it runs until the first read is a single byte. So there is some evidence that the problem is related to reading a single byte. However, I once saw a case with a multibyte transfer that failed. Its just that the single byte is the most common case, at least 100 times more often.

There is no easy way to force the FX3 to send more than one byte, so I am hoping for a C# fix.

Are there any known problems with LibUsbDotNet, or perhaps something in libusb1.0 that are known?

**Comment by mcuee** [comment]
You can probably ask in libusb-devel mailing list. There are experts on both libusb and FX2/FX3.
