### ISSUE TITLE
Is there any reason this does not target linux-arm

### ISSUE THREAD

**Issue by jrote1** [LibUsbDotNet/LibUsbDotNet#85]
Is linux-arm support possible for this library?

**Comment by doug62** [comment]
@jrote1  @gmfrederick just completed a PR, fixed a build and Rasberry now works.

**Comment by jrote1** [comment]
Thank you for doing this

**Comment by mcuee** [comment]
The latest version works well under my Raspberry Pi 400 running Ubuntu Linux 64bit.
