### ISSUE TITLE
Can't found UsbContext class.

### ISSUE THREAD

**Issue by igor-lukashenya** [LibUsbDotNet/LibUsbDotNet#88]
Hi,
I am download v2.2.29 from NuGet and can't found UsbContext class. I want implementation this [example](https://github.com/LibUsbDotNet/LibUsbDotNet/tree/master/src/Examples/Read.Only)

**Comment by ahmetgul93** [comment]
Hey, I get same error too. Have you found any solution ?

**Comment by realivanjx** [comment]
See https://github.com/LibUsbDotNet/LibUsbDotNet/issues/89
