### ISSUE TITLE
Can't found UsbContext class.

### ISSUE THREAD

**Issue by ahmetgul93** [LibUsbDotNet/LibUsbDotNet#89]
I have tried to example in repository but UsbContext is not in the nuGet package.

Could you please share what I should use instead of UsbContext ?

**Comment by qmfrederik** [comment]
Which version of the NuGet package are you using? Are you on 3.0.48-alpha?

**Comment by ahmetgul93** [comment]
2.2.29. I tried previous version 2.2.28 too

**Comment by qmfrederik** [comment]
UsbContext is a version 3.0 thing. You'll need to use 3.0.48-alpha.

**Comment by ahmetgul93** [comment]
3.0.48-alpha found the UsbContext. Thanks.

**Comment by mcuee** [comment]
Keep open as a FAQ item.

**Comment by mcuee** [comment]
Please refer to V3 example here.
https://github.com/LibUsbDotNet/LibUsbDotNet/blob/master/src/Examples/Read.Only/ReadOnly.cs
