### ISSUE TITLE
Operation not supported or unimplemented on this platform

### ISSUE THREAD

**Issue by realivanjx** [LibUsbDotNet/LibUsbDotNet#93]
Hi,

When trying to call `IUsbDevice.Open()` throws `Operation not supported or unimplemented on this platform`.

Also makes the app crashes with `AccessViolationException`.
Device im trying to connect is a samsung phone with adb enabled. What im trying to do is to implement adb in my software (works with winusb).

Platform: Windows 10
DLL: libusb-1.0.22

Thanks.

**Comment by alex-belikov** [comment]
Hi,

I have the same issue under Windows 7 x86. I'm using NuGet version 3.0.48-alpha and DLL which is included in the package.

UsbContext.List() has my device in the list. Exception is thrown when I try to Open it. Let me know what additional information can help or how to dig further.

**Comment by alex-belikov** [comment]
Ok, it's solved for me after installing this package:
**libusb-win32-devel-filter-1.2.6.0.exe**
I installed a filter for my device. But now I have a different issue....

**Comment by mcuee** [comment]
Try to use WinUSB which may be more stable and not libusb-win32 filter driver.

**Comment by mcuee** [comment]
For Windows, it is recommended to use Zadig to install drivers.
